services:
#  db:
#    image: postgres
#    container_name: 'my-commerce-db'
#    ports:
#      - 5432:5432
#    env_file:
#      - .env
#    volumes:
#      - db:/var/lib/postgresql/data
  cache:
    image: redis
    container_name: 'my-commerce-cache'
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
#volumes:
#  db:
